# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-08 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(verbose_name='公文通编号')),
                ('type', models.CharField(max_length=10, verbose_name='类别')),
                ('unit', models.CharField(max_length=20, verbose_name='发文单位')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('date', models.DateField(verbose_name='日期')),
            ],
            options={
                'verbose_name': '标题',
                'ordering': ['-date'],
                'verbose_name_plural': '标题',
            },
        ),
    ]
