# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(verbose_name='公文通编号')),
                ('type', models.CharField(max_length=10, verbose_name='类别')),
                ('unit', models.CharField(max_length=20, verbose_name='发文单位')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('date', models.DateField(verbose_name='日期')),
                ('content', models.CharField(max_length=10000, verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '标题',
                'verbose_name': '标题',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
