# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-01 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_auto_20161019_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='canWatch',
            field=models.BooleanField(default=False, verbose_name='是否展示'),
        ),
    ]
