# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-02 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_item_canwatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-date'], 'permissions': (('manager', '公文通信息管理员'),), 'verbose_name': '标题', 'verbose_name_plural': '标题'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='canWatch',
            new_name='isShow',
        ),
        migrations.AddField(
            model_name='item',
            name='hasFile',
            field=models.BooleanField(default=False, verbose_name='是否有附件'),
        ),
        migrations.AddField(
            model_name='item',
            name='isTop',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
